name: staging deploy
on:
  push:
    branches: 
      - master
jobs:

  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Run Deployment to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA }}
          script: |
            ls
