name: staging deploy
on:
  push:
    branches: 
      - master
jobs:

  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Run Deployment to staging
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA }}
          script_stop: true
          envs: GITHUB_SHA, REGISTRY, DOC_API_TOKEN
          script: |
            docker ps
            ls
            export DOCKER_FRONTEND_IMAGE_TAG=faf99bc
            echo $DOCKER_FRONTEND_IMAGE_TAG
            
            docker-compose -f docker-compose.staging.yaml up -d frontend
            docker-compose -f docker-compose.staging.yaml restart nginx
            
 
 
